# Generated by Django 6.0.5 on 2026-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0002_subject_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
